Repository ppc64le-cloud/kubevirt, pull requests merged in 2024-02, with the labels that each got.

#3 vm examples and nodelabeller update
  cmd/virt-launcher/node-labeller/node-labeller.sh
  examples/vm_fedora_large_ppc64le.yaml
  examples/vm_fedora_ppc64le.yaml
  kubevirt-operator.yaml
Labels: size/XXL

#4 replace COPY with ADD for fedora cloud qcow2
  containerimages/Dockerfile
Labels: size/XS

#5 Ppc64le updated with ssh to vm using the public key and md file to create image
  README_PPC64LE.md
  examples/vm_fedora_ppc64le.yaml
Labels: size/L
